// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationKind } from "./AnnotationKind";

export type Annotation = { kind: AnnotationKind, at: [number, number], size?: [number, number] | null, points?: Array<[number, number]>, text?: string | null, color?: string | null, anchor?: string | null, };
