// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Conflict = { ours_label: string, theirs_label: string, ours: string, theirs: string, line: number, };
