// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntryKind } from "./DirEntryKind";

export type FolderEntry = { name: string, path: string, kind: DirEntryKind, engine: string | null, has_layout: boolean, };
