// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Conflict } from "./Conflict";
import type { Sidecar } from "./Sidecar";

export type LayoutState = { "status": "none" } | { "status": "ok", sidecar: Sidecar, } | { "status": "conflict", conflict: Conflict, } | { "status": "invalid", message: string, };
