// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pin = { x: number, y: number, fingerprint?: string | null, auto?: [number, number] | null, };
