// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JarSource } from "./JarSource";

export type PlantUmlProbe = { java: string | null, jar: string | null, version: string | null, jarSource: JarSource, };
