// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SequenceHints = { lifeline_order?: Array<string>, lifeline_gap?: { [key in string]: number }, message_gap?: { [key in string]: number }, };
